apiVersion: v2
name: langwatch-helm
description: Helm chart for LangWatch application
type: application
appVersion: 2.2.0
version: 2.3.0
annotations:
  category: Observability
  keywords: ai,observability,monitoring,secrets
  maintainers: LangWatch Team
dependencies:
  - name: postgresql
    version: 16.4.9
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.chartManaged
  - name: redis
    version: 18.0.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.chartManaged
  - name: opensearch
    version: 2.35.0
    repository: https://opensearch-project.github.io/helm-charts/
    condition: opensearch.chartManaged
  - name: prometheus
    version: 2.1.23
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: prometheus.chartManaged
