name: sdk-python-ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'sdk-python/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "sdk-python/uv.lock"

      - name: Setup Python UV
        working-directory: sdk-python
        run: uv sync --all-groups --all-extras

      - name: Run tests
        working-directory: sdk-python
        env:
          LANGWATCH_DEBUG: "true"
          LANGWATCH_API_KEY: ${{ secrets.PYTHON_SDK_LANGWATCH_API_KEY }}
          AZURE_OPENAI_API_KEY: ${{ secrets.PYTHON_SDK_AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.PYTHON_SDK_AZURE_OPENAI_ENDPOINT }}
          GEMINI_API_KEY: ${{ secrets.PYTHON_SDK_GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.PYTHON_SDK_GROQ_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.PYTHON_SDK_OPENAI_API_KEY }}
        run: uv run pytest
